insert into exclusion(sic,description) values ('01610','Support activities for crop production');
insert into exclusion(sic,description) values ('01700','Hunting, trapping and related service activities');
insert into exclusion(sic,description) values ('09900','Support activities for other mining and quarrying');
insert into exclusion(sic,description) values ('11070','Manufacture of soft drinks; production of mineral waters and other bottled waters');
insert into exclusion(sic,description) values ('14190','Manufacture of other wearing apparel and accessories');
insert into exclusion(sic,description) values ('20590','Manufacture of other chemical products n.e.c.');
insert into exclusion(sic,description) values ('20590','The manufacture and supply of chemical sample extraction and purification products.');
insert into exclusion(sic,description) values ('22190','Manufacture of other rubber products');
insert into exclusion(sic,description) values ('22190','A group engaged in the manufacture and factoring of components and services in the markets of fire and security.');
insert into exclusion(sic,description) values ('22290','Manufacture of other plastic products');
insert into exclusion(sic,description) values ('23310','Development, manufacture and marketing of home consumer products within the UK, South Africa, and the rest of the world.');
insert into exclusion(sic,description) values ('25730','Manufacture of tools');
insert into exclusion(sic,description) values ('25930','A holding company.');
insert into exclusion(sic,description) values ('25930','The provision of contract manufacturing services.');
insert into exclusion(sic,description) values ('25930','The manufacture of tubular welding wires, welding equipment, equipment for use in the manufacture of steel, and trading in raw materials.');
insert into exclusion(sic,description) values ('26309','The development, supply&maintenance of technologies used in advanced security, surveillance&ruggedised electronic applications.');
insert into exclusion(sic,description) values ('26400','Manufacture of consumer electronics');
insert into exclusion(sic,description) values ('26400','The rental, retail and service of radio, television, video and hi-fi equipment.');
insert into exclusion(sic,description) values ('28120','Manufacture of fluid power equipment');
insert into exclusion(sic,description) values ('28150','Manufacture of bearings, gears, gearing and driving elements');
insert into exclusion(sic,description) values ('28220','The design of remote marine systems.');
insert into exclusion(sic,description) values ('28290','Research and Development.');
insert into exclusion(sic,description) values ('28990','Provides manufacturers&printers with the ablility to code, mark or print data, information or graphical images onto their products or packaging at high speed typically in line in the manufacturing or printing process.');
insert into exclusion(sic,description) values ('29100','A group engaged in the design and construction of racing cars, participation in motor racing events throughout the world.');
insert into exclusion(sic,description) values ('29100','Manufacture of motor vehicles');
insert into exclusion(sic,description) values ('29100','The design and construction of racing cars, motor sport consultancy and participation in motor racing events,');
insert into exclusion(sic,description) values ('31090','Manufacture of other furniture');
insert into exclusion(sic,description) values ('32500','Manufacture of medical and dental instruments and supplies');
insert into exclusion(sic,description) values ('32500','Manufacture, distribution and servicing of specialist medical and industrial equipment.');
insert into exclusion(sic,description) values ('32990','Other manufacturing n.e.c.');
insert into exclusion(sic,description) values ('41100','Development of building projects');
insert into exclusion(sic,description) values ('45200','A group engaged in the sale, repair and servicing of taxis, motor dealers, development and manufacturing of electronic taximeters, renting and servicing of electronic taximeters.');
insert into exclusion(sic,description) values ('45310','Wholesale trade of motor vehicle parts and accessories');
insert into exclusion(sic,description) values ('46410','Wholesale of textiles');
insert into exclusion(sic,description) values ('46900','Non-specialised wholesale trade');
insert into exclusion(sic,description) values ('47721','Retail sale of footwear in specialised stores');
insert into exclusion(sic,description) values ('47910','Retail sale via mail order houses or via Internet');
insert into exclusion(sic,description) values ('58290','Other software publishing');
insert into exclusion(sic,description) values ('62020','Computer consultancy activities');
insert into exclusion(sic,description) values ('64910','Financial leasing');
insert into exclusion(sic,description) values ('68320','Management of real estate on a fee or contract basis');
insert into exclusion(sic,description) values ('70100','Activities of head offices');
insert into exclusion(sic,description) values ('70100','The provision of solutions for secure, energy-efficient generation, transmission&distribution of electricity&for increasing productivity in industrial, commercial operation.');
insert into exclusion(sic,description) values ('70229','Management consultancy activities (other than financial management)');
insert into exclusion(sic,description) values ('71121','A leading provider of electronic design and build solutions.');
insert into exclusion(sic,description) values ('72190','Other research and experimental development on natural sciences and engineering');
insert into exclusion(sic,description) values ('72190','Research and development.');
insert into exclusion(sic,description) values ('75000','Veterinary activities');
insert into exclusion(sic,description) values ('77390','Renting and leasing of other machinery, equipment and tangible goods n.e.c.');
insert into exclusion(sic,description) values ('82990','Other business support service activities n.e.c.');
insert into exclusion(sic,description) values ('90040','Operation of arts facilities');
insert into exclusion(sic,description) values ('96090','Other personal service activities n.e.c.');
